Repository cdm-mps/creativestudio, pull requests merged in 2024-01, with the labels that each got.

#6 Banner Grid & Image Element
  fe/app/components/BannerGrid/BannerGrid.models.tsx
  fe/app/components/BannerGrid/BannerGrid.tsx
  fe/app/components/ImageElement/ImageElement.models.tsx
  fe/app/components/ImageElement/ImageElement.tsx
  fe/tailwind.config.ts
Labels: enhancement

#7 CDM-12: Setup i18n and create LocaleSwitcher component
  .babelrc
  fe/.eslintrc.json
  fe/app/[locale]/layout.tsx
  fe/app/[locale]/page.tsx
  fe/app/assets/icons/Dot.tsx
  fe/app/components/LocaleSwitcher/LocaleSwitcher.models.tsx
  fe/app/components/LocaleSwitcher/LocaleSwitcher.tsx
  fe/app/layout.tsx
  fe/config.ts
  fe/i18n.ts
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
  fe/i18n/navigation.ts
  fe/middleware.ts
  fe/next.config.js
  fe/package.json
  package.json
Labels: enhancement, chore

#8 CDM-24: Create Bullet Point component
  README.md
  fe/app/components/BulletPoint/BulletPoint.models.tsx
  fe/app/components/BulletPoint/BulletPoint.tsx
  package.json
Labels: enhancement

#9 CDM-25: Create Modal component
  fe/app/assets/icons/CloseIcon.tsx
  fe/app/components/Modal/Modal.models.tsx
  fe/app/components/Modal/Modal.tsx
Labels: enhancement

#10 CDM-17: New Divider component
  fe/app/components/Divider/Divider.models.tsx
  fe/app/components/Divider/Divider.tsx
  fe/tailwind.config.ts
Labels: enhancement

#11 CDM-14/37: New ContactInfo component and Design System page
  README.md
  fe/app/[locale]/design-system/page.tsx
  fe/app/[locale]/layout.tsx
  fe/app/assets/icons/Instagram.tsx
  fe/app/components/ContactInfo/ContactInfo.models.tsx
  fe/app/components/ContactInfo/ContactInfo.tsx
  fe/app/components/Divider/Divider.tsx
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: documentation, enhancement

#13 CDM-19: New QuoteElement and QuoteSlider components
  fe/app/[locale]/design-system/page.tsx
  fe/app/components/Quote/Quote.models.tsx
  fe/app/components/Quote/QuoteElement.tsx
  fe/app/components/Quote/QuoteSlider.tsx
Labels: enhancement

#17 CDM-33: Create Footer component
  fe/app/[locale]/layout.tsx
  fe/app/[locale]/page.tsx
  fe/app/assets/icons/MadeByDarwinIcon.tsx
  fe/app/components/Footer/Footer.tsx
  fe/app/components/LocaleSwitcher/LocaleSwitcher.tsx
  fe/config.ts
Labels: enhancement

#12 CDM-31: Create Button Filter and Button Filter Element component
  fe/app/components/ButtonFilter/ButtonFilter.models.tsx
  fe/app/components/ButtonFilter/ButtonFilter.tsx
  fe/app/components/ButtonFilterElement/ButtonFilterElement.models.ts
  fe/app/components/ButtonFilterElement/ButtonFilterElement.tsx
  fe/tsconfig.json
Labels: enhancement

#16 CDM-28: Create Details component
  fe/app/[locale]/design-system/page.tsx
  fe/app/components/Details/Details.models.ts
  fe/app/components/Details/Details.tsx
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement

#18 CDM-30: Create Button component
  fe/app/[locale]/design-system/layout.tsx
  fe/app/[locale]/design-system/page.tsx
  fe/app/components/Button/Button.models.tsx
  fe/app/components/Button/Button.tsx
  fe/app/components/Footer/Footer.tsx
  fe/app/components/shared/Loader/Loader.tsx
Labels: enhancement

#23 CDM-15: RoundArrowButton Component
  fe/app/assets/icons/StickHead.tsx
  fe/app/components/RoundArrowButton/RoundArrowButton.models.ts
  fe/app/components/RoundArrowButton/RoundArrowButton.tsx
Labels: enhancement

#24 CDM-41: TabElement & TabElementRow Components
  fe/app/components/Tabs/TabElement/TabElement.models.ts
  fe/app/components/Tabs/TabElement/TabElement.tsx
  fe/app/components/Tabs/Tabs.models.ts
  fe/app/components/Tabs/Tabs.tsx
Labels: enhancement

#20 CDM-34: Create Navbar component
  fe/app/[locale]/about-us/page.tsx
  fe/app/[locale]/business-workshops/page.tsx
  fe/app/[locale]/calendar/page.tsx
  fe/app/[locale]/contacts/page.tsx
  fe/app/[locale]/creative-workshops/page.tsx
  fe/app/[locale]/design-system/page.tsx
  fe/app/[locale]/layout.tsx
  fe/app/[locale]/mentors/page.tsx
  fe/app/[locale]/page.tsx
  fe/app/assets/CreativeStudio.png
  fe/app/assets/icons/MenuIcon.tsx
  fe/app/components/Divider/Divider.tsx
  fe/app/components/Footer/Footer.tsx
  fe/app/components/Navbar/MenuOptions/MenuOptions.models.ts
  fe/app/components/Navbar/MenuOptions/MenuOptions.tsx
  fe/app/components/Navbar/Navbar.tsx
  fe/app/components/Title/Title.tsx
  fe/app/utils/getMenuOptions.ts
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement

#32 CDM-49: DateInfo new xs size
  fe/app/components/DateInfo/DateInfo.models.ts
  fe/app/components/DateInfo/DateInfo.tsx
Labels: bug

#29 CDM-48: Event Info Component
  fe/app/assets/icons/Info.tsx
  fe/app/components/EventInfo/EventInfo.models.ts
  fe/app/components/EventInfo/EventInfo.tsx
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement

#19 CDM-20: New Mentor related components
  fe/app/[locale]/design-system/page.tsx
  fe/app/assets/images/BeneditaPereira.png
  fe/app/assets/images/CarolinaLeite.png
  fe/app/components/DateInfo/DateInfo.tsx
  fe/app/components/ImageElement/ImageElement.models.ts
  fe/app/components/ImageElement/ImageElement.tsx
  fe/app/components/Mentor/Mentor.models.ts
  fe/app/components/Mentor/Mentor.tsx
  fe/app/components/MentorEventBar/MentorEventBar.models.tsx
  fe/app/components/MentorEventBar/MentorEventBar.tsx
  fe/app/components/MentorIdentifier/MentorIdentifier.tsx
  fe/app/components/MentorIdentifier/MentorIdentifierProps.models.ts
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
  fe/tsconfig.json
Labels: enhancement

#34 CDM-27: Create Stepper component
  fe/app/[locale]/design-system/page.tsx
  fe/app/assets/icons/Avatar.tsx
  fe/app/assets/icons/Splitter.tsx
  fe/app/components/Navbar/MenuOptions/MenuOptions.tsx
  fe/app/components/Stepper/Stepper.models.ts
  fe/app/components/Stepper/Stepper.tsx
  fe/app/components/StepperElement/StepperElement.models.ts
  fe/app/components/StepperElement/StepperElement.tsx
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement

#36 CDM-23: Create Schedule related components
  fe/app/[locale]/design-system/page.tsx
  fe/app/assets/icons/Clock.tsx
  fe/app/components/EnumBulletPoint/EnumBulletPoint.models.ts
  fe/app/components/EnumBulletPoint/EnumBulletPoint.tsx
  fe/app/components/Schedule/Schedule.models.ts
  fe/app/components/Schedule/ScheduleElement.tsx
Labels: enhancement

#35 CDM-18: Create new CategoryBar related components
  fe/app/[locale]/creative-workshops/artistic-residence/page.tsx
  fe/app/[locale]/creative-workshops/business-workshop/page.tsx
  fe/app/[locale]/creative-workshops/creative-talks/page.tsx
  fe/app/[locale]/creative-workshops/edition/page.tsx
  fe/app/[locale]/creative-workshops/masterclass/page.tsx
  fe/app/[locale]/creative-workshops/page.tsx
  fe/app/[locale]/creative-workshops/workshop/page.tsx
  fe/app/[locale]/design-system/page.tsx
  fe/app/assets/images/CreativeStudio.png
  fe/app/components/BreadcrumbsTitle/BreadcrumbsTitle.tsx
  fe/app/components/CategoryBar/CategoryBar.models.ts
  fe/app/components/CategoryBar/CategoryBarList.tsx
  fe/app/components/CategoryBar/CatergoryBarElement.tsx
  fe/app/components/Navbar/Navbar.tsx
  fe/app/model/Category.ts
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement

#27 CDM-43: Team Element & TeamElementRow Components
  fe/app/components/Divider/Divider.models.ts
  fe/app/components/Divider/Divider.tsx
  fe/app/components/TeamElement/TeamElement.models.ts
  fe/app/components/TeamElement/TeamElement.tsx
  fe/app/components/TeamElementRow/TeamElementRow.models.ts
  fe/app/components/TeamElementRow/TeamElementRow.tsx
Labels: enhancement

#28 CDM-44: EventElement & EventGrid components
  fe/app/components/EventElement/EventElement.models.ts
  fe/app/components/EventElement/EventElement.tsx
  fe/app/components/EventGrid/EventGrid.models.ts
  fe/app/components/EventGrid/EventGrid.tsx
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
  fe/tailwind.config.ts
Labels: enhancement

#30 CDM-42: NewsElement & NewsSlider components
  fe/app/components/NewsElement/NewsElement.models.ts
  fe/app/components/NewsElement/NewsElement.tsx
  fe/app/components/NewsSlider/NewsSlider.models.ts
  fe/app/components/NewsSlider/NewsSlider.tsx
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement

#33 CDM-51: NewsElement | Add category icon & onClick event
  fe/app/components/NewsElement/NewsElement.models.ts
  fe/app/components/NewsElement/NewsElement.tsx
Labels: bug

#40 CDM-58: Add examples of all components
  fe/app/[locale]/design-system/page.tsx
  fe/app/assets/icons/StickHead.tsx
  fe/app/components/EventInfo/EventInfo.models.ts
Labels: improvement

#39 CDM-54: Hamburguer menu with instagram link
  fe/app/assets/icons/Instagram.tsx
  fe/app/assets/icons/InstagramO.tsx
  fe/app/components/Navbar/Navbar.tsx
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement, improvement

#38 CDM-21: Create new submition component
  fe/app/[locale]/design-system/page.tsx
  fe/app/assets/images/IconCreativeStud.png
  fe/app/components/SubmitionStatus/SubmitionStatus.models.ts
  fe/app/components/SubmitionStatus/SubmitionStatus.tsx
Labels: enhancement

#41 CDM-45: Filters component
  fe/app/[locale]/design-system/page.tsx
  fe/app/[locale]/layout.tsx
  fe/app/assets/icons/Times.tsx
  fe/app/components/Filters/Filters.models.ts
  fe/app/components/Filters/Filters.tsx
  fe/app/components/Filters/components/Tag/Tag.models.ts
  fe/app/components/Filters/components/Tag/Tag.tsx
  fe/app/globals.css
  fe/i18n/messages/en.json
  fe/i18n/messages/pt.json
Labels: enhancement

#42 CDM-16: New Sponsors component
  fe/app/[locale]/design-system/page.tsx
  fe/app/[locale]/page.tsx
  fe/app/assets/images/fb.png
  fe/app/assets/images/hbo.png
  fe/app/assets/images/nos.png
  fe/app/assets/images/vercel.png
  fe/app/components/Sponsors/Sponsors.models.tsx
  fe/app/components/Sponsors/Sponsors.tsx
Labels: enhancement
